version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elasticsearch
    environment:
      - node.name=node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password#123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - services
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYTpTX2xwaGx2WFFmQ0trUWUyTXBwdU9n
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - services

networks:
  services:
    external: true
