version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password#123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    # networks:
    #   - containers_default
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password#123
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    #  elasticsearch:
        # condition: service_healthy
    # networks:
    #   - containers_default

# networks:
#   elastic:
#     driver: bridge
