
services:
  lavinmq:
    image: cloudamqp/lavinmq:pr-1102
    container_name: lavinmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password#123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/data/lavinmq:/var/lib/lavinmq
    restart: on-failure:3
    networks:
      - services

networks:
  services:
    external: true
