version: '3.8'

services:
  mysql:
    image: mysql:lts
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - containers
    environment:
      MYSQL_ROOT_PASSWORD: password#123
      MYSQL_DATABASE: public
      MYSQL_USER: admin
      MYSQL_PASSWORD: password#123
    volumes:
     - /data/mysql:/var/lib/mysql
    # command: [--ignore-db-dir=lost+found]

networks:
  containers:
    driver: bridge
    name: services