version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password#123
      MYSQL_DATABASE: public
      MYSQL_USER: suheyl
      MYSQL_PASSWORD: password#123
#    volumes:
#      - /var/data/mysql:/var/lib/mysql

volumes:
  mysql_data:
    driver: local