version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      # POSTGRES_DB: mydatabase
      POSTGRES_ROOT_PASSWORD: password#123
    ports:
      - "5432:5432"
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data
    restart: on-failure:3
    networks:
      - services

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin#123
    ports:
      - "8001:80"
    depends_on:
      - postgres
    restart: on-failure:3
    networks:
      - services

networks:
  services:
    driver: bridge

