version: '3.8'

services:
  redis:
    image: redis:7.0.11
    container_name: redis
    restart: always
    networks:
      - containers
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /data/redis:/data
      - /data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD="password#123"

volumes:
  redis-data:
    driver: local

networks:
  containers:
    driver: bridge
    name: services