
services:
  redis:
    image: redis:7.0.11
    container_name: redis
    restart: always
    networks:
      - services
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /var/data/redis:/data
      - /var/data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD="password#123"

networks:
  services:
    external: true
