version: '3.8'

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - containers
    environment:
      - SCYLLA_PASSWORD="password#123"
    volumes:
      - /var/data/scylladb:/var/lib/scylla
    command: [
      "--smp", "1",                     # Use a single CPU for simplicity
      "--memory", "2G",                 # Allocate 2GB of RAM
      "--overprovisioned", "1",         # Run in developer mode
      "--developer-mode", "1"           # Enable developer mode
    ]

networks:
  containers:
    driver: bridge