
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - services
    environment:
      ZOO_PASSWORD: 'password#123'
    volumes:
      - '/data/zookeeper:/var/lib/zookeeper'
      - '/data/zookeeper:/data'
      - '/data/zookeeper:/logs'
      - './zoo.cfg:/zookeeper/conf/zoo.cfg'
    command:
      - sh
      - -c
      - "cp /conf/zoo.cfg /conf/zoo.cfg.bak && cp /conf/zoo.cfg /zookeeper/conf/zoo.cfg && bin/zkServer.sh start-foreground"

networks:
  services:
    external: true
