storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: 100

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@orbit/*':
    access: $all
    publish: $authenticated
    proxy: false

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
    allow_offline: false

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
