
services:
  postgres:
    image: fs-postgres:17.5
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'password#123'
    ports:
      - "5432:5432"
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - services

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@postgres.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin#123'
    ports:
      - "8001:80"
    depends_on:
      - postgres
    restart: on-failure:3
    volumes:
      - /var/data/pgadmin:/var/lib/pgadmin
    networks:
      - services

networks:
  services:
    external: true



